### ISSUE TITLE
Make a new release

### ISSUE THREAD

**Issue by mbrodala** [actionjack/puppet-mailcatcher#21]
Given the fact that there are [quite a lot of changes](https://github.com/actionjack/puppet-mailcatcher/compare/v0.1.10...ec8f98822ee63c9be9688fe6b08e1db331f5184d) since the last release (0.1.10 from September 2014) maybe a new version could be released.

**Comment by actionjack** [comment]
@mbrodala I just cut a new release for you.

**Comment by mbrodala** [comment]
Thanks a lot. :-)
