### ISSUE TITLE
Mailcatcher service fails to start - CentOS 7, Puppet 3.7.4

### ISSUE THREAD

**Issue by stanicek** [actionjack/puppet-mailcatcher#23]
Error: Could not start Service[mailcatcher]: Execution of '/sbin/service mailcatcher start' returned 127: /etc/init.d/mailcatcher: line 23: /usr/bin/mailcatcher: No such file or directory
Wrapped exception:
Execution of '/sbin/service mailcatcher start' returned 127: /etc/init.d/mailcatcher: line 23: /usr/bin/mailcatcher: No such file or directory
Error: /Stage[main]/Mailcatcher::Service/Service[mailcatcher]/ensure: change from stopped to running failed: Could not start Service[mailcatcher]: Execution of '/sbin/service mailcatcher start' returned 127: /etc/init.d/mailcatcher: line 23: /usr/bin/mailcatcher: No such file or directory

Mailcatcher is installed in /usr/local/bin/mailcatcher, but in service scripts there is path /usr/bin/mailcatcher.

**Comment by stanicek** [comment]
I see problem in following condition in params.pp. When I enclose version number in quotes everything works fine.

Original:
```
case $::operatingsystemmajrelease {
        7: {
```
Works for me:
```
case $::operatingsystemmajrelease {
        '7': {
```

**Comment by hdi-kw** [comment]
Interesting. I have puppet 3.7.1 and facter 2.2.0 and had no problem without the quotes. But it also works with the quotes. So just change it!
